# Generated by Django 3.2.12 on 2022-02-16 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishlists', '0004_auto_20220209_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='shared_users',
            field=models.ManyToManyField(related_name='shared_wishlist_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
