# Generated by Django 3.2.12 on 2022-02-17 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0005_wishlist_shared_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='shared_users',
            new_name='shared_with_users',
        ),
    ]
